ALTER VIEW VW_Resumen_nomina
as

select 
AÑO, MES, SUM(SALARIOS) SALARIOS, SUM(BENEFICIOS) BENEFICIOS, SUM(DEDUCCIONES) DEDUCCIONES, SUM(IMPUESTOS) IMPUESTOS, SUM(DESCUENTOS) DESCUENTOS, SUM(APORTES) APORTES,
DEPTO, DSCRIPTN
from ( 
SELECT 
YEAR(F.F_PAGO) AÑO, MONTH(F.F_PAGO) MES,
A.ID_DB, A.ID_PLANI, A.VALOR SALARIOS, 0.00 BENEFICIOS, 0.00 DEDUCCIONES, 0.00 IMPUESTOS, 0.00 DESCUENTOS, 0.00 APORTES,
A.TIPO, A.CLASIFICA,'SALARIO' CLASE,F.F_PAGO,
'SUELDM' CODIGO, 'SALARIO MENSUAL' DESCRIPCIONB, B.EMPLOYID, B.FRSTNAME, B.MIDLNAME, B.LASTNAME, 
C.DEPRTMNT DEPTO, C.DSCRIPTN
from GP_NOMINA..GP_NOMINA_NOMINAS_HISTORICO A
INNER JOIN INE01..UPR00100 B ON
A.EMPLOYID = B.EMPLOYID
INNER JOIN GP_NOMINA..GP_NOMINA_ENCABEZADO F ON
A.ID_PLANI = F.ID_PLANILLA
INNER JOIN GP_NOMINA..GP_NOMINA_DETALLE G ON
A.ID_PLANI = G.ID_PLANILLA AND
A.EMPLOYID = G.EMPLOYID
INNER JOIN INE01..UPR40300 C ON
G.DEPRTMNT = C.DEPRTMNT
where
A.ID_CALC = 'SUELDM'

UNION ALL

SELECT 
YEAR(F.F_PAGO) AÑO, MONTH(F.F_PAGO) MES,
A.ID_DB, A.ID_PLANI, 0.00 SALARIOS, A.VALOR BENEFICIOS, 0.00 DEDUCCIONES, 0.00 IMPUESTOS, 0.00 DESCUENTOS, 0.00 APORTES,
A.TIPO, A.CLASIFICA,'BENEFICIOS' CLASE,F.F_PAGO,
E.BENEFIT CODIGO, E.DSCRIPTN DESCRIPCION,
B.EMPLOYID, B.FRSTNAME, B.MIDLNAME, B.LASTNAME, 
C.DEPRTMNT DEPTO, C.DSCRIPTN
from GP_NOMINA..GP_NOMINA_NOMINAS_HISTORICO A
INNER JOIN INE01..UPR00100 B ON
A.EMPLOYID = B.EMPLOYID
INNER JOIN INE01..UPR40800 E ON
A.ID_CALC = E.BENEFIT
INNER JOIN GP_NOMINA..GP_NOMINA_ENCABEZADO F ON
A.ID_PLANI = F.ID_PLANILLA
INNER JOIN GP_NOMINA..GP_NOMINA_DETALLE G ON
A.ID_PLANI = G.ID_PLANILLA AND
A.EMPLOYID = G.EMPLOYID
INNER JOIN INE01..UPR40300 C ON
G.DEPRTMNT = C.DEPRTMNT

UNION ALL

select 
YEAR(F.F_PAGO) AÑO, MONTH(F.F_PAGO) MES,
A.ID_DB, A.ID_PLANI, 0.00 SALARIOS, 0.00 BENEFICIOS, 0.00 DEDUCCIONES, 0.00 IMPUESTOS, 0.00 DESCUENTOS, A.VALOR APORTES, 
A.TIPO, A.CLASIFICA,'APORTE PATRONO' CLASE,F.F_PAGO,
E.DEDUCTON CODIGO, E.DSCRIPTN DESCRIPCION,
B.EMPLOYID, B.FRSTNAME, B.MIDLNAME, B.LASTNAME, 
C.DEPRTMNT DEPTO, C.DSCRIPTN
from GP_NOMINA..GP_NOMINA_NOMINAS_HISTORICO A
INNER JOIN INE01..UPR00100 B ON
A.EMPLOYID = B.EMPLOYID
INNER JOIN ine01..UPR40900 E ON
A.ID_CALC = E.DEDUCTON
INNER JOIN GP_NOMINA..GP_NOMINA_ENCABEZADO F ON
A.ID_PLANI = F.ID_PLANILLA
INNER JOIN GP_NOMINA..GP_NOMINA_DETALLE G ON
A.ID_PLANI = G.ID_PLANILLA AND
A.EMPLOYID = G.EMPLOYID
INNER JOIN INE01..UPR40300 C ON
G.DEPRTMNT = C.DEPRTMNT
where
A.ID_CALC IN
(select DEDUCTON from ine01..UPR40900
 where DEDUCTON IN ('ISSSPM','UPISSP','IPSFAP','CONPM','CREPM','INSAF'))

UNION ALL

select
YEAR(F.F_PAGO) AÑO, MONTH(F.F_PAGO) MES,
A.ID_DB, A.ID_PLANI, 0.00 SALARIOS, 0.00 BENEFICIOS, 0.00 DEDUCCIONES, 0.00 IMPUESTOS, A.VALOR DESCUENTOS, 0.00 APORTES, 
A.TIPO, A.CLASIFICA,'DESCUENTO PERSONAL' CLASE, F.F_PAGO,
E.DEDUCTON CODIGO, E.DSCRIPTN DESCRIPCION,
B.EMPLOYID, B.FRSTNAME, B.MIDLNAME, B.LASTNAME, 
C.DEPRTMNT DEPTO, C.DSCRIPTN
from GP_NOMINA..GP_NOMINA_NOMINAS_HISTORICO A
INNER JOIN INE01..UPR00100 B ON
A.EMPLOYID = B.EMPLOYID
INNER JOIN ine01..UPR40900 E ON
A.ID_CALC = E.DEDUCTON
INNER JOIN GP_NOMINA..GP_NOMINA_ENCABEZADO F ON
A.ID_PLANI = F.ID_PLANILLA
INNER JOIN GP_NOMINA..GP_NOMINA_DETALLE G ON
A.ID_PLANI = G.ID_PLANILLA AND
A.EMPLOYID = G.EMPLOYID
INNER JOIN INE01..UPR40300 C ON
G.DEPRTMNT = C.DEPRTMNT
where
A.ID_CALC IN
(select DEDUCTON from ine01..UPR40900
 where DEDUCTON NOT IN ('ISSSPM','UPISSP','IPSFAP','CONPM','CREPM','INSAF'))
AND
A.CLASIFICA = 5 

UNION ALL

select
YEAR(F.F_PAGO) AÑO, MONTH(F.F_PAGO) MES,
A.ID_DB, A.ID_PLANI, 0.00 SALARIOS, 0.00 BENEFICIOS, A.VALOR DEDUCCIONES, 0.00 IMPUESTOS, 0.00 DESCUENTOS, 0.00 APORTES, 
A.TIPO, A.CLASIFICA,'DEDUCCION EMPLEADO' CLASE, F.F_PAGO,
E.DEDUCTON CODIGO, E.DSCRIPTN DESCRIPCION,
B.EMPLOYID, B.FRSTNAME, B.MIDLNAME, B.LASTNAME, 
C.DEPRTMNT DEPTO, C.DSCRIPTN
from GP_NOMINA..GP_NOMINA_NOMINAS_HISTORICO A
INNER JOIN INE01..UPR00100 B ON
A.EMPLOYID = B.EMPLOYID
INNER JOIN ine01..UPR40900 E ON
A.ID_CALC = E.DEDUCTON
INNER JOIN GP_NOMINA..GP_NOMINA_ENCABEZADO F ON
A.ID_PLANI = F.ID_PLANILLA
INNER JOIN GP_NOMINA..GP_NOMINA_DETALLE G ON
A.ID_PLANI = G.ID_PLANILLA AND
A.EMPLOYID = G.EMPLOYID
INNER JOIN INE01..UPR40300 C ON
G.DEPRTMNT = C.DEPRTMNT
where
A.ID_CALC IN
(select DEDUCTON from ine01..UPR40900
 where DEDUCTON NOT IN ('ISSSPM','UPISSP','IPSFAP','CONPM','CREPM','INSAF'))
AND
A.CLASIFICA = 3 

UNION ALL

select
YEAR(F.F_PAGO) AÑO, MONTH(F.F_PAGO) MES,
A.ID_DB, A.ID_PLANI,  0.00 SALARIOS, 0.00 BENEFICIOS, 0.00 DEDUCCIONES, 0.00 IMPUESTOS, A.VALOR DESCUENTOS, 0.00 APORTES,  
A.TIPO, A.CLASIFICA,'DESCUENTO PERSONAL' CLASE, F.F_PAGO,
E.DEDUCTON CODIGO, E.DSCRIPTN DESCRIPCION,
B.EMPLOYID, B.FRSTNAME, B.MIDLNAME, B.LASTNAME, 
C.DEPRTMNT DEPTO, C.DSCRIPTN
from GP_NOMINA..GP_NOMINA_NOMINAS_HISTORICO A
INNER JOIN INE01..UPR00100 B ON
A.EMPLOYID = B.EMPLOYID
INNER JOIN ine01..UPR40900 E ON
A.ID_CALC = E.DEDUCTON
INNER JOIN GP_NOMINA..GP_NOMINA_ENCABEZADO F ON
A.ID_PLANI = F.ID_PLANILLA
INNER JOIN GP_NOMINA..GP_NOMINA_DETALLE G ON
A.ID_PLANI = G.ID_PLANILLA AND
A.EMPLOYID = G.EMPLOYID
INNER JOIN INE01..UPR40300 C ON
G.DEPRTMNT = C.DEPRTMNT
where
A.ID_CALC IN
(select DEDUCTON from ine01..UPR40900
 where DEDUCTON NOT IN ('ISSSPM','UPISSP','IPSFAP','CONPM','CREPM','INSAF'))
AND
A.CLASIFICA = 1

UNION ALL

select
YEAR(F.F_PAGO) AÑO, MONTH(F.F_PAGO) MES,
A.ID_DB, A.ID_PLANI, 0.00 SALARIOS, 0.00 BENEFICIOS, A.VALOR DEDUCCIONES, 0.00 IMPUESTOS, 0.00 DESCUENTOS, 0.00 APORTES, 
A.TIPO, A.CLASIFICA,'DEDUCCION EMPLEADO' CLASE, F.F_PAGO,
E.DEDUCTON CODIGO, E.DSCRIPTN DESCRIPCION,
B.EMPLOYID, B.FRSTNAME, B.MIDLNAME, B.LASTNAME, 
C.DEPRTMNT DEPTO, C.DSCRIPTN
from GP_NOMINA..GP_NOMINA_NOMINAS_HISTORICO A
INNER JOIN INE01..UPR00100 B ON
A.EMPLOYID = B.EMPLOYID
INNER JOIN ine01..UPR40900 E ON
A.ID_CALC = E.DEDUCTON
INNER JOIN GP_NOMINA..GP_NOMINA_ENCABEZADO F ON
A.ID_PLANI = F.ID_PLANILLA
INNER JOIN GP_NOMINA..GP_NOMINA_DETALLE G ON
A.ID_PLANI = G.ID_PLANILLA AND
A.EMPLOYID = G.EMPLOYID
INNER JOIN INE01..UPR40300 C ON
G.DEPRTMNT = C.DEPRTMNT
where
A.ID_CALC IN
(select DEDUCTON from ine01..UPR40900
 where DEDUCTON NOT IN ('ISSSPM','UPISSP','IPSFAP','CONPM','CREPM','INSAF'))
AND
A.CLASIFICA = 8 

UNION ALL

select
YEAR(F.F_PAGO) AÑO, MONTH(F.F_PAGO) MES,
A.ID_DB, A.ID_PLANI, 0.00 SALARIOS, 0.00 BENEFICIOS, 0.00 DEDUCCIONES, A.VALOR IMPUESTOS, 0.00 DESCUENTOS, 0.00 APORTES, 
A.TIPO, A.CLASIFICA,'IMPUESTOS' CLASE, F.F_PAGO,
E.DEDUCTON CODIGO, E.DSCRIPTN DESCRIPCION,
B.EMPLOYID, B.FRSTNAME, B.MIDLNAME, B.LASTNAME, 
C.DEPRTMNT DEPTO, C.DSCRIPTN
from GP_NOMINA..GP_NOMINA_NOMINAS_HISTORICO A
INNER JOIN INE01..UPR00100 B ON
A.EMPLOYID = B.EMPLOYID
INNER JOIN ine01..UPR40900 E ON
A.ID_CALC = E.DEDUCTON
INNER JOIN GP_NOMINA..GP_NOMINA_ENCABEZADO F ON
A.ID_PLANI = F.ID_PLANILLA
INNER JOIN GP_NOMINA..GP_NOMINA_DETALLE G ON
A.ID_PLANI = G.ID_PLANILLA AND
A.EMPLOYID = G.EMPLOYID
INNER JOIN INE01..UPR40300 C ON
G.DEPRTMNT = C.DEPRTMNT
where
A.ID_CALC IN
(select DEDUCTON from ine01..UPR40900
 where DEDUCTON NOT IN ('ISSSPM','UPISSP','IPSFAP','CONPM','CREPM','INSAF'))
AND
A.CLASIFICA = 2

UNION ALL

select
YEAR(F.F_PAGO) AÑO, MONTH(F.F_PAGO) MES,
A.ID_DB, A.ID_PLANI, 0.00 SALARIOS, 0.00 BENEFICIOS, 0.00 DEDUCCIONES, A.VALOR IMPUESTOS, 0.00 DESCUENTOS, 0.00 APORTES, 
A.TIPO, A.CLASIFICA,'IMPUESTOS' CLASE, F.F_PAGO,
A.ID_CALC CODIGO, 'RENTA' DESCRIPCION,
B.EMPLOYID, B.FRSTNAME, B.MIDLNAME, B.LASTNAME, 
C.DEPRTMNT DEPTO, C.DSCRIPTN
from GP_NOMINA..GP_NOMINA_NOMINAS_HISTORICO A
INNER JOIN INE01..UPR00100 B ON
A.EMPLOYID = B.EMPLOYID
INNER JOIN GP_NOMINA..GP_NOMINA_ENCABEZADO F ON
A.ID_PLANI = F.ID_PLANILLA
INNER JOIN GP_NOMINA..GP_NOMINA_DETALLE G ON
A.ID_PLANI = G.ID_PLANILLA AND
A.EMPLOYID = G.EMPLOYID
INNER JOIN INE01..UPR40300 C ON
G.DEPRTMNT = C.DEPRTMNT
where
A.ID_CALC LIKE 'REN%'
) as Nomina
GROUP BY AÑO, MES, DEPTO, DSCRIPTN










 
